version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    volumes:
      - events_mssql:/var/opt/mssql
      # - ./setup.sql:/usr/config/setup.sql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
      - MSSQL_DB=events_service
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Passw@rd
      - MSSQL_DB_AUDIT_LOG=events_service_audit_log

volumes:
  events_mssql:
  # sql_server:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   # volumes:
  #   #     - events_mssql:/var/opt/mssql
  #   container_name: sql_server
  #   environment:
  #     SA_PASSWORD: 6Xy3LkV7!9lo2^h
  #     ACCEPT_EULA: Y
  #   ports:
  #     - "1433:1433"