// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using labSchool.Context;

#nullable disable

namespace labSchool.Migrations
{
    [DbContext(typeof(LabSchoolContext))]
    [Migration("20230414124812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("labSchool.Models.Aluno", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Nascimento")
                        .HasColumnOrder(4);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome")
                        .HasColumnOrder(2);

                    b.Property<float>("NotaProcessoSeletivo")
                        .HasColumnType("REAL")
                        .HasColumnName("Nota")
                        .HasColumnOrder(7);

                    b.Property<string>("SituacaoMatricula")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Situação_Matrícula")
                        .HasColumnOrder(6);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefone")
                        .HasColumnOrder(3);

                    b.Property<int>("TotalAtendimentosPedagogicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Atendimentos")
                        .HasColumnOrder(8);

                    b.HasKey("Codigo");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Aluno", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Cpf = "11839750073",
                            DataNascimento = new DateTime(2014, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Bart Simpson",
                            NotaProcessoSeletivo = 3.5f,
                            SituacaoMatricula = "IRREGULAR",
                            Telefone = "11-11111-1212",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 2,
                            Cpf = "17158947076",
                            DataNascimento = new DateTime(2012, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lisa Simpson",
                            NotaProcessoSeletivo = 10f,
                            SituacaoMatricula = "ATIVO",
                            Telefone = "11-22222-2222",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 3,
                            Cpf = "63701210020",
                            DataNascimento = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Meggie Simpson",
                            NotaProcessoSeletivo = 9f,
                            SituacaoMatricula = "ATIVO",
                            Telefone = "12-20002-2200",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 4,
                            Cpf = "30119137062",
                            DataNascimento = new DateTime(2014, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Milhouse Van Houten",
                            NotaProcessoSeletivo = 8f,
                            SituacaoMatricula = "ATIVO",
                            Telefone = "11-33333-2222",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 5,
                            Cpf = "95704094015",
                            DataNascimento = new DateTime(2007, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Nelson Muntz",
                            NotaProcessoSeletivo = 2f,
                            SituacaoMatricula = "INATIVO",
                            Telefone = "11-44333-4444",
                            TotalAtendimentosPedagogicos = 0
                        });
                });

            modelBuilder.Entity("labSchool.Models.Pedagogo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Nascimento")
                        .HasColumnOrder(4);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome")
                        .HasColumnOrder(2);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefone")
                        .HasColumnOrder(3);

                    b.Property<int>("TotalAtendimentosPedagogicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Atendimentos")
                        .HasColumnOrder(6);

                    b.HasKey("Codigo");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Pedagogo", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Cpf = "62316840086",
                            DataNascimento = new DateTime(2000, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "John Snow",
                            Telefone = "11-67333-4454",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 2,
                            Cpf = "49850253053",
                            DataNascimento = new DateTime(2004, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sansa Stark",
                            Telefone = "22-22333-4454",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 3,
                            Cpf = "39125106015",
                            DataNascimento = new DateTime(1990, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Tyrion Lannister",
                            Telefone = "33-77333-4454",
                            TotalAtendimentosPedagogicos = 0
                        },
                        new
                        {
                            Codigo = 4,
                            Cpf = "89089606009",
                            DataNascimento = new DateTime(1995, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sandor Clegane",
                            Telefone = "11-33333-2222",
                            TotalAtendimentosPedagogicos = 0
                        });
                });

            modelBuilder.Entity("labSchool.Models.Professor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Nascimento")
                        .HasColumnOrder(4);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado")
                        .HasColumnOrder(6);

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Experiência")
                        .HasColumnOrder(7);

                    b.Property<string>("FormacaoAcademica")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Formação_Acadêmica")
                        .HasColumnOrder(8);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome")
                        .HasColumnOrder(2);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefone")
                        .HasColumnOrder(3);

                    b.HasKey("Codigo");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Professor", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Cpf = "40539019011",
                            DataNascimento = new DateTime(1982, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ATIVO",
                            Experiencia = "FULL_STACK",
                            FormacaoAcademica = "MESTRADO",
                            Nome = "Walter White",
                            Telefone = "14-22998-1882"
                        },
                        new
                        {
                            Codigo = 2,
                            Cpf = "96107295097",
                            DataNascimento = new DateTime(1997, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ATIVO",
                            Experiencia = "BACK_END",
                            FormacaoAcademica = "GRADUAÇÃO_INCOMPLETA",
                            Nome = "Jesse Pinkman",
                            Telefone = "44-11111-1992"
                        },
                        new
                        {
                            Codigo = 3,
                            Cpf = "70685977005",
                            DataNascimento = new DateTime(1984, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ATIVO",
                            Experiencia = "FULL_STACK",
                            FormacaoAcademica = "MESTRADO",
                            Nome = "Hank Schrader",
                            Telefone = "44-11111-1002"
                        },
                        new
                        {
                            Codigo = 4,
                            Cpf = "57408927085",
                            DataNascimento = new DateTime(1977, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "INATIVO",
                            Experiencia = "FRONT_END",
                            FormacaoAcademica = "GRADUAÇÃO_COMPLETA",
                            Nome = "Gustavo Fring",
                            Telefone = "44-11001-1002"
                        },
                        new
                        {
                            Codigo = 5,
                            Cpf = "86940162062",
                            DataNascimento = new DateTime(1980, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ATIVO",
                            Experiencia = "FULL_STACK",
                            FormacaoAcademica = "MESTRADO",
                            Nome = "Saul Goodman",
                            Telefone = "44-11998-1882"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
