// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ex_003.Context;

#nullable disable

namespace ex_003.Migrations
{
    [DbContext(typeof(BercarioContext))]
    [Migration("20230405185110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ex_003.Models.Bebe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Altura")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mae_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parto_Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Peso_Nascimento")
                        .HasPrecision(4, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mae_Id");

                    b.HasIndex("Parto_Id");

                    b.ToTable("Bebe", (string)null);
                });

            modelBuilder.Entity("ex_003.Models.Mae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mae", (string)null);
                });

            modelBuilder.Entity("ex_003.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Celular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("ex_003.Models.Parto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Parto")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Horario_Parto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Medico_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Medico_Id");

                    b.ToTable("Parto", (string)null);
                });

            modelBuilder.Entity("ex_003.Models.Bebe", b =>
                {
                    b.HasOne("ex_003.Models.Mae", "Mae")
                        .WithMany("Bebes")
                        .HasForeignKey("Mae_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MAE_BEBE");

                    b.HasOne("ex_003.Models.Parto", "Parto")
                        .WithMany("Bebes")
                        .HasForeignKey("Parto_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PARTO_BEBE");

                    b.Navigation("Mae");

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("ex_003.Models.Parto", b =>
                {
                    b.HasOne("ex_003.Models.Medico", "Medico")
                        .WithMany("Partos")
                        .HasForeignKey("Medico_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEDICO_PARTO");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ex_003.Models.Mae", b =>
                {
                    b.Navigation("Bebes");
                });

            modelBuilder.Entity("ex_003.Models.Medico", b =>
                {
                    b.Navigation("Partos");
                });

            modelBuilder.Entity("ex_003.Models.Parto", b =>
                {
                    b.Navigation("Bebes");
                });
#pragma warning restore 612, 618
        }
    }
}
